#define F(NAME,TARGET) class NAME { \
    allowedTargets = TARGET; \
};

#define ANYONE 0
#define CLIENT 1
#define SERVER 2
#define HC HC_Life

class CfgRemoteExec {
    class Functions {
        mode = 1;
        jip = 0;

        /* Client only functions */
        F(life_fnc_jail,CLIENT)
        F(life_fnc_jailTroll,CLIENT)
        F(life_fnc_moveIn,CLIENT)
        F(life_fnc_restrain,CLIENT)
        F(life_fnc_restrainCiv,CLIENT)
        F(life_fnc_robPerson,CLIENT)
        F(life_fnc_removeLicenses,CLIENT)
        F(life_fnc_searchClient,CLIENT)
        F(TON_fnc_player_query,CLIENT)
        F(life_fnc_knockedOut,CLIENT)
        F(life_fnc_robReceive,CLIENT)
        F(life_fnc_tazeSound,CLIENT)
        F(life_fnc_copSiren,CLIENT)
        F(life_fnc_medicSiren,CLIENT)
        F(life_fnc_giveDiff,CLIENT)
        F(life_fnc_gangInvite,CLIENT)
        F(TON_fnc_clientGangKick,CLIENT)
        F(TON_fnc_clientGangLeader,CLIENT)
        F(TON_fnc_clientGangLeft,CLIENT)
        F(life_fnc_lightHouse,CLIENT)
        F(life_fnc_medicRequest,CLIENT)
        F(life_fnc_revived,CLIENT)
        F(life_fnc_receiveItem,CLIENT)
        F(life_fnc_receiveMoney,CLIENT)
        F(TON_fnc_clientGetKey,CLIENT)
        F(life_fnc_soundDevice,CLIENT)
        F(life_fnc_wireTransfer,CLIENT)
        F(life_fnc_pickupMoney,CLIENT)
        F(life_fnc_pickupItem,CLIENT)
        F(life_fnc_gangCreated,CLIENT)
        F(life_fnc_gangDisbanded,CLIENT)
        F(life_fnc_jailMe,CLIENT)
        F(life_fnc_jailTrollMe,CLIENT)
        F(SOCK_fnc_dataQuery,CLIENT)
        F(SOCK_fnc_insertPlayerInfo,CLIENT)
        F(SOCK_fnc_requestReceived,CLIENT)
        F(life_fnc_adminid,CLIENT)
        F(life_fnc_impoundMenu,CLIENT)
        F(life_fnc_garageRefund,CLIENT)
        F(life_fnc_addVehicle2Chain,CLIENT)
        F(life_fnc_vehicleAnimate,CLIENT)
        F(life_fnc_spikeStripEffect,CLIENT)
        F(life_fnc_bountyReceive,CLIENT)
        F(life_fnc_wantedList,CLIENT)
        F(life_fnc_admininfo,CLIENT)
        F(life_fnc_licenseCheck,CLIENT)
        F(life_fnc_licensesRead,CLIENT)
        F(life_fnc_copSearch,CLIENT)
        F(life_fnc_copLights,CLIENT)
        F(life_fnc_ticketPrompt,CLIENT)
        F(life_fnc_ticketPaid,CLIENT)
        F(life_fnc_freezePlayer,CLIENT)
        F(life_fnc_mediclights,CLIENT)
        F(life_fnc_mecanolights,CLIENT)
        F(life_fnc_hideObj,CLIENT)
        F(life_fnc_itemSellMoney,CLIENT)
        F(life_fnc_vehicleAHMenu,CLIENT)
        F(life_fnc_getNbrVehGarage,CLIENT)
        F(life_fnc_friendInvitePlayer,CLIENT)
        F(life_fnc_friendAnswerPlayer,CLIENT)
        F(life_fnc_buyWantedIndice,CLIENT)
		F(life_fnc_updateMarket,CLIENT)
		F(life_fnc_brokenLeg,CLIENT)
		F(life_fnc_callCop,CLIENT)
		F(life_fnc_adminSleepPlayer,CLIENT)
		F(life_fnc_fixBloodPack,CLIENT)
		F(life_fnc_fixBrokenLeg,CLIENT)
		F(life_fnc_handleInv,CLIENT)
		F(life_fnc_smartphone,CLIENT)
		F(life_fnc_smartphoneUpdate,CLIENT)
		F(life_fnc_receiveMessage,CLIENT)
		F(life_fnc_dropADN,CLIENT)
		F(life_fnc_searchADN,CLIENT)
		F(life_fnc_shootNear,CLIENT)
		F(life_fnc_copSearchRemove,CLIENT)
		F(life_fnc_copSearchPlayer,CLIENT)
		F(life_fnc_playSound,CLIENT)
		F(life_fnc_AAN,CLIENT)
		F(life_fnc_updateMarketWeapon,CLIENT)
		F(life_fnc_initFullGang,CLIENT)
		F(life_fnc_weaponReceive,CLIENT)
		F(life_fnc_commandToxic,CLIENT)
		F(life_fnc_toxicAddAction,CLIENT)
		F(life_fnc_alarmCop,CLIENT)
		F(life_fnc_vehicleCraft,CLIENT)
		F(life_fnc_askBill,CLIENT)
		F(life_fnc_paidBill,CLIENT)
		F(life_fnc_warnGangCapture,CLIENT)
		F(life_fnc_moneyFunction,CLIENT)
		F(life_fnc_organStole,CLIENT)
		F(life_fnc_fetchSkills,CLIENT)
		

        /* Server only functions */
        F(BIS_fnc_effectKilledSecondaries,SERVER)
        F(bis_fnc_execvm,SERVER)
        F(bis_fnc_curatorrespawn,SERVER)
        F(life_fnc_wantedBounty,SERVER)
        F(TON_fnc_getID,SERVER)
        F(life_fnc_jailSys,SERVER)
        F(life_fnc_jailTrollSys,SERVER)
        F(life_fnc_wantedRemove,SERVER)
        F(life_fnc_wantedAdd,SERVER)
        F(life_fnc_JailPlayer,SERVER)
        F(TON_fnc_insertGang,SERVER)
        F(TON_fnc_removeGang,SERVER)
        F(TON_fnc_updateGang,SERVER)
        F(TON_fnc_updateHouseTrunk,SERVER)
        F(TON_fnc_sellHouse,SERVER)
        F(TON_fnc_managesc,SERVER)
        F(TON_fnc_spikeStrip,SERVER)
        F(life_fnc_wantedCrimes,SERVER)
        F(life_fnc_wantedFetch,SERVER)
        F(life_fnc_wantedProfUpdate,SERVER)
        F(DB_fnc_queryRequest,SERVER)
        F(DB_fnc_insertRequest,SERVER)
        F(DB_fnc_updatePartial,SERVER)
        F(DB_fnc_updateRequest,SERVER)
        F(TON_fnc_chopShopSell,SERVER)
        F(TON_fnc_setObjVar,SERVER)
        F(TON_fnc_keyManagement,SERVER)
        F(TON_fnc_vehicleDelete,SERVER)
        F(TON_fnc_spawnVehicle,SERVER)
        F(TON_fnc_getVehicles,SERVER)
        F(TON_fnc_getAllVehicles,SERVER)
        F(TON_fnc_vehicleStore,SERVER)
        F(SPY_fnc_observe,SERVER)
        F(TON_fnc_cleanupRequest,SERVER)
        F(TON_fnc_updateHouseContainers,SERVER)
        F(SPY_fnc_cookieJar,SERVER)
        F(TON_fnc_vehicleCreate,SERVER)
        F(TON_fnc_addHouse,SERVER)
        F(TON_fnc_addContainer,SERVER)
        F(TON_fnc_sellHouseContainer,SERVER)
        F(TON_fnc_deleteDBContainer,SERVER)
        F(TON_fnc_vehicleUpdate,SERVER)
        F(TON_fnc_vAH_update,SERVER)
		F(TON_fnc_HV_updateVeh,SERVER)
		F(TON_fnc_HV_changeOwner,SERVER)
		F(TON_fnc_countVehGarage,SERVER)
		F(TON_fnc_getUpdate,SERVER)
		F(TON_fnc_changePrice,SERVER)
		F(TON_fnc_playerLogged,SERVER)
		F(TON_fnc_InsureCar,SERVER)
		F(TON_fnc_playerRapported,SERVER)
		F(TON_fnc_pardonRapport,SERVER)
		F(A3Log,SERVER)
		F(TON_fnc_getMessages,SERVER)
		F(TON_fnc_sendMessages,SERVER)
		F(TON_fnc_deletemessages,SERVER)
		F(TON_fnc_checkADN,SERVER)
		F(TON_fnc_stealTimer,SERVER)
		F(TON_fnc_rentHouse,SERVER)
		F(TON_fnc_buyAlarm,SERVER)
		F(TON_fnc_showrentHouse,SERVER)
		F(TON_fnc_askMarketWeapon,SERVER)
		F(TON_fnc_buyWeaponMarket,SERVER)
		F(TON_fnc_queryPlayerFullGang,SERVER)
		F(TON_fnc_manageToxic,SERVER)
		F(TON_fnc_supplyCheck,SERVER)
		F(TON_fnc_updateGangArea,SERVER)
		F(TON_fnc_queryPlayerSkills,SERVER)


        /* HeadlessClient only functions */
        F(HC_fnc_addContainer,HC)
        F(HC_fnc_addHouse,HC)
        F(HC_fnc_chopShopSell,HC)
        F(HC_fnc_deleteDBContainer,HC)
        F(HC_fnc_getVehicles,HC)
        F(HC_fnc_insertGang,HC)
        F(HC_fnc_queryPlayerFullGang,HC)
        F(HC_fnc_insertRequest,HC)
        F(HC_fnc_insertVehicle,HC)
        F(HC_fnc_jailSys,HC)
        F(HC_fnc_jailTrollSys,HC)
        F(HC_fnc_jailPlayer,HC)
        F(HC_fnc_keyManagement,HC)
        F(HC_fnc_queryRequest,HC)
        F(HC_fnc_removeGang,HC)
        F(HC_fnc_sellHouse,HC)
        F(HC_fnc_sellHouseContainer,HC)
        F(HC_fnc_spawnVehicle,HC)
        F(HC_fnc_spikeStrip,HC)
        F(HC_fnc_updateGang,HC)
        F(HC_fnc_updateHouseContainers,HC)
        F(HC_fnc_updateHouseTrunk,HC)
        F(HC_fnc_updatePartial,HC)
        F(HC_fnc_updateRequest,HC)
        F(HC_fnc_vehicleCreate,HC)
        F(HC_fnc_vehicleDelete,HC)
        F(HC_fnc_vehicleStore,HC)
        F(HC_fnc_vehicleUpdate,HC)
        F(HC_fnc_wantedAdd,HC)
        F(HC_fnc_wantedBounty,HC)
        F(HC_fnc_wantedCrimes,HC)
        F(HC_fnc_wantedFetch,HC)
        F(HC_fnc_wantedProfUpdate,HC)
        F(HC_fnc_wantedRemove,HC)
		F(HC_fnc_rentHouse,HC)
		F(HC_fnc_showrentHouse,HC)
		F(HC_fnc_queryPlayerSkills,HC)
		F(HC_fnc_updateGangArea,HC)
		F(HC_fnc_checkADN,HC)
		F(HC_fnc_supplyCheck,HC)
		F(HC_fnc_manageToxic,HC)
		F(HC_fnc_stealTimer,HC)
		F(HC_fnc_countVehGarage,HC)
		F(HC_fnc_deleteMessages,HC)
		F(HC_fnc_sendMessages,HC)
		F(HC_fnc_getMessages,HC)
		F(HC_fnc_InsureCar,HC)

        /* Functions for everyone */
        F(life_fnc_broadcast,ANYONE)
        F(life_fnc_vAH_reciever,ANYONE)
        F(life_fnc_animSync,ANYONE)
        F(life_fnc_demoChargeTimer,ANYONE)
        F(life_fnc_demoToxicTimer,ANYONE)
        F(life_fnc_corpse,ANYONE)
        F(life_fnc_colorVehicle,ANYONE)
        F(life_fnc_lockVehicle,ANYONE)
        F(life_fnc_flashbang,ANYONE)
        F(life_fnc_lacrymo,ANYONE)
        F(life_fnc_jumpFnc,ANYONE)
        F(SPY_fnc_notifyAdmins,ANYONE)
        F(life_fnc_setFuel,ANYONE)
        F(life_fnc_pulloutVeh,ANYONE)
        F(life_fnc_pushFunction,ANYONE)
        F(life_fnc_simDisable,ANYONE)
		
       


    };

    class Commands {
        mode = 1;
        jip = 0;

        F(setFuel,ANYONE)
        F(addWeapon,ANYONE)
        F(addMagazine,ANYONE)
        F(addPrimaryWeaponItem,ANYONE)
        F(addHandgunItem,ANYONE)
		F(call,ANYONE)
    };
};
